########################################
##      用于生成数字+字母的验证码
########################################

COMMON:
    TEXT_CREATOR : random       # 随机生成:random, 语料生成:corpus
    GENERATOR : text            # 保存轮廓的:contour, 只保存标签: text<---

CORPUS:
    FILE: data/corpus.txt       # 语料路径，如果是多个文件，请事先合并
    MAX_LENGHT: 104857600       # 最大加载大小，默认是100M

RESOURCE :
    FONT_DIR: data/fonts
    BACKGROUND_DIR: data/backgrounds
    CHARSET: config/charset.captcha.txt # 只有数字和英文的字符集<---

MAX_GENERATE_NUM : 1000000000   # 生成的最大的整形数
MAX_LENGTH : 4                  # 可能的最大长度（字符数）<---
MIN_LENGTH : 4                  # 可能的最小长度（字符数）<---
MAX_FONT_SIZE : 28              # 最大的字体
MIN_FONT_SIZE : 18              # 最小的字体号

# 颜色的算法是，产生一个基准，然后RGB上下浮动FONT_COLOR_NOISE
MAX_FONT_COLOR : 128            # 最大的可能颜色
FONT_COLOR_NOISE : 10           # 最大的可能颜色


MAX_SPECIAL_NUM : 5             # 特殊字符的个数
MAX_BLANK_NUM : 5               # 字之间随机的空格数量
TEXT_WIDTH_PAD : 50             # 文字的左右pad
TEXT_HEIGHT_PAD : 10            # 文字的上下pad

# 各种可能性的概率
POSSIBILITY_BLANK : 0           # 有空格的概率<---
POSSIBILITY_SPECIAL : 0         # 插入一些特殊字符的概率<---

POSSIBILITY_TEXT:
    normal : 1                  # 最普通的情况（汉字+数字+英文+符号）<---
    number : 0                  # 需要产生的纯数字<---
    english : 0                 # 需要产生的英语<---
    date : 0                    # 需要产生的纯日期<---
    single : 0                  # 单字的比例<---